# Generated by Django 4.1.6 on 2023-02-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets', models.CharField(default='', max_length=80)),
                ('seats', models.CharField(default='', max_length=80)),
                ('namefirst', models.CharField(default='', max_length=80)),
                ('namelast', models.CharField(default='', max_length=80)),
                ('emailcust', models.EmailField(default='', max_length=80)),
                ('phone', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
