# Generated by Django 4.1.6 on 2023-02-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_detailsbmo_detailsroger_detailsscotia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detailsroger',
            new_name='Detailsrogers',
        ),
    ]
